
package es.uned.scc.grados.appdist.trabajos.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.3
 * Tue Jan 12 14:03:27 CET 2021
 * Generated source version: 3.1.3
 */

@XmlRootElement(name = "setSignalParameters", namespace = "http://ws.trabajos.appdist.grados.scc.uned.es/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "setSignalParameters", namespace = "http://ws.trabajos.appdist.grados.scc.uned.es/")

public class SetSignalParameters {

    @XmlElement(name = "signal_parameters")
    private es.uned.scc.grados.appdist.trabajos.signal.model.data.SignalParameters signal_parameters;

    public es.uned.scc.grados.appdist.trabajos.signal.model.data.SignalParameters getSignal_parameters() {
        return this.signal_parameters;
    }

    public void setSignal_parameters(es.uned.scc.grados.appdist.trabajos.signal.model.data.SignalParameters newSignal_parameters)  {
        this.signal_parameters = newSignal_parameters;
    }

}

