
package es.uned.scc.grados.appdist.trabajos.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.3
 * Tue Jan 12 14:03:27 CET 2021
 * Generated source version: 3.1.3
 */

@XmlRootElement(name = "stop", namespace = "http://ws.trabajos.appdist.grados.scc.uned.es/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "stop", namespace = "http://ws.trabajos.appdist.grados.scc.uned.es/")

public class Stop {


}

